version: '3.8'

services:
  backend:
    build: ./titansearch-backend
    container_name: titansearch-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  frontend:
    build: ./titansearch-frontend
    container_name: titansearch-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
