services:
  - type: web
    name: repolens
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: GITHUB_TOKEN
        sync: true
      - key: GEMINI_API_KEY
        sync: true
