services:
  - type: web
    name: repolens-backend
    env: docker
    dockerfilePath: Dockerfile
    rootDir: titansearch-backend
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: GITHUB_TOKEN
        sync: true
      - key: GEMINI_API_KEY
        sync: true

  - type: static
    name: repolens-frontend
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    rootDir: titansearch-frontend
    envVars:
      - key: VITE_API_BASE_URL
        value: https://repolens-backend.onrender.com
