spring:
  datasource:
    url: ${DATABASE_URL:${SPRING_DATASOURCE_URL:}}
    username: ${DATABASE_USERNAME:${SPRING_DATASOURCE_USERNAME:}}
    password: ${DATABASE_PASSWORD:${SPRING_DATASOURCE_PASSWORD:}}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.titansearch: DEBUG
